# =============================================================================
# modules/report_generator.py — Downloadable Farming Report (PDF + JSON)
# =============================================================================
import os
import json
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

REPORTS_DIR = Path(os.getenv("REPORTS_DIR", "./reports"))
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_farming_report(profile: dict, chat_history: list, weather: dict,
                             market_data: dict, recommendations: dict) -> dict:
    """
    Generate a comprehensive farming report.
    Returns paths to both PDF and JSON report files.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    farm_name = profile.get("farm_name", "Farm").replace(" ", "_")
    base_filename = f"report_{farm_name}_{timestamp}"

    json_path = _generate_json_report(base_filename, profile, chat_history,
                                       weather, market_data, recommendations)
    pdf_path = _generate_pdf_report(base_filename, profile, chat_history,
                                     weather, market_data, recommendations)

    return {
        "json_path": str(json_path),
        "pdf_path": str(pdf_path) if pdf_path else None,
        "filename": base_filename,
        "generated_at": datetime.now().isoformat(),
    }


def _generate_json_report(filename: str, profile: dict, chat_history: list,
                           weather: dict, market_data: dict, recommendations: dict) -> Path:
    """Generate structured JSON report."""
    report = {
        "report_metadata": {
            "title": "AI Smart Farming Advisory Report — KrishiMitra",
            "generated_at": datetime.now().isoformat(),
            "generated_by": "KrishiMitra AI Agent v2.0",
            "report_id": filename,
        },
        "farm_profile": profile,
        "weather_summary": weather,
        "market_prices": market_data,
        "recommendations": recommendations,
        "chat_summary": [
            {"role": msg.get("role"), "content": msg.get("content", "")[:500]}
            for msg in chat_history[-20:]  # Last 20 messages
        ],
        "disclaimer": (
            "This report is generated by AI for advisory purposes only. "
            "Always consult with a certified agronomist or your local Krishi Vigyan Kendra "
            "before making major farming decisions."
        ),
    }

    path = REPORTS_DIR / f"{filename}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2, default=str)

    logger.info(f"JSON report generated: {path}")
    return path


def _generate_pdf_report(filename: str, profile: dict, chat_history: list,
                          weather: dict, market_data: dict, recommendations: dict) -> Path | None:
    """Generate PDF report using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch, cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                         Table, TableStyle, HRFlowable)
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        path = REPORTS_DIR / f"{filename}.pdf"
        doc = SimpleDocTemplate(str(path), pagesize=A4,
                                 rightMargin=1.5*cm, leftMargin=1.5*cm,
                                 topMargin=2*cm, bottomMargin=2*cm)

        styles = getSampleStyleSheet()
        # Custom styles
        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                      fontSize=20, textColor=colors.HexColor("#2d6a4f"),
                                      alignment=TA_CENTER, spaceAfter=6)
        subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"],
                                         fontSize=11, textColor=colors.HexColor("#52796f"),
                                         alignment=TA_CENTER, spaceAfter=12)
        heading_style = ParagraphStyle("Heading", parent=styles["Heading2"],
                                        fontSize=13, textColor=colors.HexColor("#1b4332"),
                                        spaceBefore=12, spaceAfter=6)
        body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                     fontSize=10, leading=14)
        green_accent = colors.HexColor("#2d6a4f")

        story = []

        # ── Header ────────────────────────────────────────────────────────
        story.append(Paragraph("🌾 KrishiMitra — Smart Farming Advisory Report", title_style))
        story.append(Paragraph(
            f"Generated on {datetime.now().strftime('%d %B %Y, %I:%M %p')}",
            subtitle_style
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=green_accent))
        story.append(Spacer(1, 12))

        # ── Farm Profile ──────────────────────────────────────────────────
        story.append(Paragraph("Farm Profile", heading_style))
        profile_data = [
            ["Farm Name", profile.get("farm_name", "N/A")],
            ["Farmer Name", profile.get("farmer_name", "N/A")],
            ["Location", profile.get("location", "N/A")],
            ["Farm Area", f"{profile.get('area_acres', 'N/A')} acres"],
            ["Soil Type", profile.get("soil_type", "N/A")],
            ["Irrigation", profile.get("irrigation_type", "N/A")],
            ["Current Crops", ", ".join(profile.get("current_crops", []))],
        ]
        table = Table(profile_data, colWidths=[4.5*cm, 12*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#d8f3dc")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1b4332")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#b7e4c7")),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f0faf4")]),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)
        story.append(Spacer(1, 12))

        # ── Weather Summary ────────────────────────────────────────────────
        if weather:
            story.append(Paragraph("Weather Summary", heading_style))
            weather_text = (
                f"Location: {weather.get('location')} | "
                f"Temperature: {weather.get('temperature')}°C | "
                f"Humidity: {weather.get('humidity')}% | "
                f"Conditions: {weather.get('description')} | "
                f"Season: {weather.get('season', 'N/A')}"
            )
            story.append(Paragraph(weather_text, body_style))

            if weather.get("advisory"):
                story.append(Spacer(1, 6))
                story.append(Paragraph("<b>Agricultural Advisory:</b>", body_style))
                for adv in weather["advisory"]:
                    story.append(Paragraph(f"• {adv}", body_style))
            story.append(Spacer(1, 12))

        # ── Recommendations ────────────────────────────────────────────────
        if recommendations:
            story.append(Paragraph("Crop Recommendations", heading_style))
            for i, rec in enumerate(recommendations.get("crops", [])[:5], 1):
                story.append(Paragraph(f"{i}. {rec.get('crop', 'Unknown')} — {rec.get('rationale', '')}", body_style))
            story.append(Spacer(1, 12))

        # ── Market Prices ──────────────────────────────────────────────────
        if market_data and market_data.get("prices"):
            story.append(Paragraph("Market Price Snapshot", heading_style))
            price_table_data = [["Crop", "Market", "Min (₹)", "Max (₹)", "Modal (₹)"]]
            for p in market_data["prices"][:10]:
                price_table_data.append([
                    p.get("crop", ""), p.get("market", ""),
                    str(p.get("min_price", "")), str(p.get("max_price", "")),
                    str(p.get("modal_price", "")),
                ])
            pt = Table(price_table_data, colWidths=[4*cm, 5*cm, 2.5*cm, 2.5*cm, 2.5*cm])
            pt.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), green_accent),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#b7e4c7")),
                ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, colors.HexColor("#f0faf4")]),
                ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(pt)
            story.append(Spacer(1, 12))

        # ── Chat Summary ───────────────────────────────────────────────────
        recent_chats = [m for m in chat_history[-10:] if m.get("role") in ("user", "assistant")]
        if recent_chats:
            story.append(Paragraph("Recent Advisory Conversation", heading_style))
            for msg in recent_chats:
                role = "You" if msg.get("role") == "user" else "KrishiMitra"
                content = msg.get("content", "")[:300]
                style = ParagraphStyle(
                    f"{role}Style", parent=body_style,
                    textColor=colors.HexColor("#1b4332") if role == "KrishiMitra" else colors.black,
                    leftIndent=10 if role == "KrishiMitra" else 0,
                )
                story.append(Paragraph(f"<b>{role}:</b> {content}", style))
                story.append(Spacer(1, 4))

        # ── Footer ─────────────────────────────────────────────────────────
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=1, color=green_accent))
        disclaimer_style = ParagraphStyle("Disclaimer", parent=body_style,
                                           fontSize=8, textColor=colors.HexColor("#6b7280"),
                                           alignment=TA_CENTER)
        story.append(Paragraph(
            "This report is generated by KrishiMitra AI Agent for advisory purposes only. "
            "Consult a certified agronomist or your local KVK before major farming decisions. "
            "Built with IBM watsonx.ai & IBM Granite.",
            disclaimer_style
        ))

        doc.build(story)
        logger.info(f"PDF report generated: {path}")
        return path

    except ImportError:
        logger.warning("ReportLab not available — PDF generation skipped.")
        return None
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return None


def list_reports() -> list:
    """List all generated reports."""
    reports = []
    for f in sorted(REPORTS_DIR.glob("*.json"), key=lambda x: x.stat().st_mtime, reverse=True):
        try:
            with open(f, "r") as rf:
                meta = json.load(rf).get("report_metadata", {})
            reports.append({
                "filename": f.stem,
                "generated_at": meta.get("generated_at", "Unknown"),
                "json_file": f.name,
                "pdf_file": f.stem + ".pdf" if (REPORTS_DIR / (f.stem + ".pdf")).exists() else None,
            })
        except Exception:
            pass
    return reports
